spring:
  datasource:
    url: jdbc:mysql://10.0.30.39:3306/db_lmp?useUnicode=true&characterEncoding=utf-8&useSSL=false&tinyInt1isBit=false
    username: usr_lmp
    password: usr_lmp
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8889